<?php

namespace Database\Seeders;

use App\Models\Barangay;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class BarangaySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $barangays = [
            [ // Atok id = 1
                'municipality_id' => 1,
                'name' => 'Poblacion',
                'code' => '01',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 1,
                'name' => 'Abiang',
                'code' => '02',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 1,
                'name' => 'Caliking',
                'code' => '03',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 1,
                'name' => 'Cattubo',
                'code' => '04',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 1,
                'name' => 'Naguey',
                'code' => '05',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 1,
                'name' => 'Paoay',
                'code' => '06',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 1,
                'name' => 'Pasdong',
                'code' => '07',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 1,
                'name' => 'Topdac',
                'code' => '08',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [ // Bakun id = 2
                'municipality_id' => 2,
                'name' => 'Poblacion',
                'code' => '01',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 2,
                'name' => 'Ampusongan',
                'code' => '02',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 2,
                'name' => 'Bagu',
                'code' => '03',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 2,
                'name' => 'Dalipey',
                'code' => '04',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 2,
                'name' => 'Gambang',
                'code' => '05',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 2,
                'name' => 'Kayapa',
                'code' => '06',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 2,
                'name' => 'Sinacbat',
                'code' => '07',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [ // Bokod id = 3
                'municipality_id' => 3,
                'name' => 'Poblacion',
                'code' => '01',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 3,
                'name' => 'Ambuclao',
                'code' => '02',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 3,
                'name' => 'Bila',
                'code' => '03',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 3,
                'name' => 'Bobok-Bisal',
                'code' => '04',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 3,
                'name' => 'Daclan',
                'code' => '05',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 3,
                'name' => 'Ekip',
                'code' => '06',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 3,
                'name' => 'Karao',
                'code' => '07',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 3,
                'name' => 'Nawal',
                'code' => '08',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 3,
                'name' => 'Pito',
                'code' => '09',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 3,
                'name' => 'Tikey',
                'code' => '10',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [ // Buguias id = 4
                'municipality_id' => 4,
                'name' => 'Poblacion',
                'code' => '01',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 4,
                'name' => 'Abatan',
                'code' => '02',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 4,
                'name' => 'Amgaleyguey',
                'code' => '03',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 4,
                'name' => 'Amlimay',
                'code' => '04',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 4,
                'name' => 'Baculongan Norte',
                'code' => '05',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 4,
                'name' => 'Baculongan Sur',
                'code' => '06',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 4,
                'name' => 'Bangao',
                'code' => '07',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 4,
                'name' => 'Buyacaoan',
                'code' => '08',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 4,
                'name' => 'Calamagan',
                'code' => '09',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 4,
                'name' => 'Catlubong',
                'code' => '10',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 4,
                'name' => 'Lengaoan',
                'code' => '11',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 4,
                'name' => 'Loo',
                'code' => '12',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 4,
                'name' => 'Natubleng',
                'code' => '13',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 4,
                'name' => 'Sebang',
                'code' => '14',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [ // Itogon id = 5
                'municipality_id' => 5,
                'name' => 'Poblacion',
                'code' => '01',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 5,
                'name' => 'Ampucao',
                'code' => '02',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 5,
                'name' => 'Dalupirip',
                'code' => '03',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 5,
                'name' => 'Gumatdang',
                'code' => '04',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 5,
                'name' => 'Loakan',
                'code' => '05',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 5,
                'name' => 'Tinongdan',
                'code' => '06',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 5,
                'name' => 'Tuding',
                'code' => '07',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 5,
                'name' => 'Ucab',
                'code' => '08',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 5,
                'name' => 'Virac',
                'code' => '09',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [ // Kabayan id = 6
                'municipality_id' => 6,
                'name' => 'Poblacion',
                'code' => '01',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 6,
                'name' => 'Adaoay',
                'code' => '02',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 6,
                'name' => 'Anchokey',
                'code' => '03',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 6,
                'name' => 'Bashoy',
                'code' => '04',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 6,
                'name' => 'Ballay',
                'code' => '05',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 6,
                'name' => 'Batan',
                'code' => '06',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 6,
                'name' => 'Duacan',
                'code' => '07',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 6,
                'name' => 'Eddet',
                'code' => '08',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 6,
                'name' => 'Gusaran',
                'code' => '09',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 6,
                'name' => 'Kabayan Barrio',
                'code' => '10',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 6,
                'name' => 'Lusod',
                'code' => '11',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 6,
                'name' => 'Pacso',
                'code' => '12',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 6,
                'name' => 'Tawangan',
                'code' => '13',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [ // Kapangan id = 7
                'municipality_id' => 7,
                'name' => 'Central',
                'code' => '01',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 7,
                'name' => 'Balakbak',
                'code' => '02',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 7,
                'name' => 'Beleng-Belis',
                'code' => '03',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 7,
                'name' => 'Boklaoan',
                'code' => '04',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 7,
                'name' => 'Cayapes',
                'code' => '05',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 7,
                'name' => 'Cuba',
                'code' => '06',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 7,
                'name' => 'Datakan',
                'code' => '07',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 7,
                'name' => 'Gadang',
                'code' => '08',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 7,
                'name' => 'Gaswiling',
                'code' => '09',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 7,
                'name' => 'Labueg',
                'code' => '10',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 7,
                'name' => 'Paykek',
                'code' => '11',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 7,
                'name' => 'Pudong',
                'code' => '12',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 7,
                'name' => 'Pongayan',
                'code' => '13',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 7,
                'name' => 'Sagubo',
                'code' => '14',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 7,
                'name' => 'Taba-ao',
                'code' => '15',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [ // Kibungan id = 8
                'municipality_id' => 8,
                'name' => 'Poblacion',
                'code' => '01',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 8,
                'name' => 'Badeo',
                'code' => '02',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 8,
                'name' => 'Lubo',
                'code' => '03',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 8,
                'name' => 'Madaymen',
                'code' => '04',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 8,
                'name' => 'Palina',
                'code' => '05',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 8,
                'name' => 'Sagpat',
                'code' => '06',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 8,
                'name' => 'Tacadang',
                'code' => '07',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [ // La Trinidad id = 9
                'municipality_id' => 9,
                'name' => 'Poblacion',
                'code' => '01',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 9,
                'name' => 'Alapang',
                'code' => '02',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 9,
                'name' => 'Alno',
                'code' => '03',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 9,
                'name' => 'Ambiong',
                'code' => '04',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 9,
                'name' => 'Bahong',
                'code' => '05',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 9,
                'name' => 'Balili',
                'code' => '06',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 9,
                'name' => 'Beckel',
                'code' => '07',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 9,
                'name' => 'Bineng',
                'code' => '08',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 9,
                'name' => 'Betag',
                'code' => '09',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 9,
                'name' => 'Cruz',
                'code' => '10',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 9,
                'name' => 'Lubas',
                'code' => '11',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 9,
                'name' => 'Pico',
                'code' => '12',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 9,
                'name' => 'Puguis',
                'code' => '13',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 9,
                'name' => 'Shilan',
                'code' => '14',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 9,
                'name' => 'Tawang',
                'code' => '15',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 9,
                'name' => 'Wangal',
                'code' => '16',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [ // Mankayan id = 10
                'municipality_id' => 10,
                'name' => 'Poblacion',
                'code' => '01',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 10,
                'name' => 'Balili',
                'code' => '02',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 10,
                'name' => 'Bedbed',
                'code' => '03',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 10,
                'name' => 'Bulalacao',
                'code' => '04',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 10,
                'name' => 'Cabiten',
                'code' => '05',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 10,
                'name' => 'Colalo',
                'code' => '06',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 10,
                'name' => 'Guinaoang',
                'code' => '07',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 10,
                'name' => 'Paco',
                'code' => '08',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 10,
                'name' => 'Suyoc',
                'code' => '09',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 10,
                'name' => 'Sapid',
                'code' => '10',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 10,
                'name' => 'Tabio',
                'code' => '11',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 10,
                'name' => 'Taneg',
                'code' => '12',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [ // Sablan id = 11
                'municipality_id' => 11,
                'name' => 'Poblacion',
                'code' => '01',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 11,
                'name' => 'Bagong',
                'code' => '02',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 11,
                'name' => 'Balluay',
                'code' => '03',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 11,
                'name' => 'Banangan',
                'code' => '04',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 11,
                'name' => 'Banengbeng',
                'code' => '05',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 11,
                'name' => 'Bayabas',
                'code' => '06',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 11,
                'name' => 'Kamog',
                'code' => '07',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 11,
                'name' => 'Pappa',
                'code' => '08',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [ // Tuba id = 12
                'municipality_id' => 12,
                'name' => 'Poblacion',
                'code' => '01',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 12,
                'name' => 'Ansagan',
                'code' => '02',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 12,
                'name' => 'Camp 1',
                'code' => '03',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 12,
                'name' => 'Camp 3',
                'code' => '04',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 12,
                'name' => 'Camp 4',
                'code' => '05',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 12,
                'name' => 'Nangalisan',
                'code' => '06',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 12,
                'name' => 'San Pascual',
                'code' => '07',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 12,
                'name' => 'Tabaan Norte',
                'code' => '08',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 12,
                'name' => 'Tabaan Sur',
                'code' => '09',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 12,
                'name' => 'Tadiangan',
                'code' => '10',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 12,
                'name' => 'Taloy Norte',
                'code' => '11',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 12,
                'name' => 'Taloy Sur',
                'code' => '12',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 12,
                'name' => 'Twin Peaks',
                'code' => '13',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [ // Tublay id = 13
                'municipality_id' => 13,
                'name' => 'Caponga (Pob.)',
                'code' => '01',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 13,
                'name' => 'Ambassador',
                'code' => '02',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 13,
                'name' => 'Ambongdolan',
                'code' => '03',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 13,
                'name' => 'Ba-ayan',
                'code' => '04',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 13,
                'name' => 'Basil',
                'code' => '05',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 13,
                'name' => 'Tublay Central',
                'code' => '06',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 13,
                'name' => 'Daclan',
                'code' => '07',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'municipality_id' => 13,
                'name' => 'Tuel',
                'code' => '08',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];
        Barangay::insert($barangays);
    }
}
